'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3625
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class UserInfoEdit

    '''<summary>
    '''form1 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Label4 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtID 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents txtID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNames 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents txtNames As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label2 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAge 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents txtAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddress 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents txtAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSave 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnQuery 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents btnQuery As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdate 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDel 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents btnDel As Global.System.Web.UI.WebControls.Button
End Class
